# Generated by Django 4.1 on 2024-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bg_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
