# Generated by Django 4.1 on 2024-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_bg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bg_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
