# Generated by Django 4.1 on 2024-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_user',
            field=models.CharField(editable=False, max_length=120, null=True, unique=True),
        ),
    ]
