# Generated by Django 4.1 on 2024-09-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_owner", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("vendor_name", models.CharField(max_length=100, null=True)),
                ("product_active", models.BooleanField(default=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("product_category", models.CharField(max_length=100)),
                ("sales_start_date", models.DateField(blank=True, null=True)),
                ("sales_end_date", models.DateField(blank=True, null=True)),
                ("support_start_date", models.DateField(blank=True, null=True)),
                ("support_end_date", models.DateField(blank=True, null=True)),
                ("unit_price", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_taxable", models.BooleanField(default=False)),
                ("usage_unit", models.CharField(max_length=50)),
                ("qty_ordered", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("handler", models.CharField(max_length=100)),
                ("quantity_in_demand", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_name", models.CharField(max_length=200, null=True)),
                ("highlights", models.TextField(null=True)),
                ("slot_timing", models.CharField(max_length=200, null=True)),
                ("sale_price", models.CharField(max_length=255, null=True)),
                ("tax", models.CharField(max_length=255, null=True)),
                (
                    "duration_in_hours",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("itenerary", models.TextField(null=True)),
                ("itenerary_time", models.TextField(null=True)),
                ("inclusions_and_exclusions", models.TextField(null=True)),
                ("additional_information", models.TextField(null=True)),
                ("time_of_the_day", models.CharField(max_length=50, null=True)),
                ("vendor_owner", models.CharField(max_length=255, null=True)),
                ("experience", models.TextField(null=True)),
                ("eligibility", models.CharField(max_length=200, null=True)),
                ("proibitions_and_limitations", models.TextField(null=True)),
                ("what_to_bring", models.TextField(null=True)),
                ("terms_and_cancellations", models.TextField(null=True)),
                ("insider_tip", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenant",
                    ),
                ),
            ],
        ),
    ]
