# Generated by Django 4.1 on 2024-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='faissindex',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
