# Generated by Django 4.1 on 2024-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField(default=list)),
                ("adj_list", models.JSONField(default=list)),
                ("curr_node", models.IntegerField(default=0)),
                ("ai_mode", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="NodeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=100)),
                ("node_data", models.JSONField()),
            ],
        ),
    ]
