# Generated by Django 4.1 on 2024-09-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
        ("node_temps", "0002_initial"),
    ]

    operations = [
      
    ]
