# Generated by Django 4.1 on 2024-09-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('node_temps', '0003_nodetemplate_fallback_count_and_more'),
    ]

    operations = [
    ]
