# Generated by Django 4.1 on 2024-10-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('node_temps', '0004_nodetemplate_fallback_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='fallback_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='fallback_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
