# Generated by Django 4.1 on 2024-09-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0002_initial"),
        ("interaction", "0002_initial"),
    ]

    operations = [
        
    ]
