# Generated by Django 4.1 on 2024-09-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contacts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant", "0001_initial"),
        ("interaction", "0003_calls_call_to_calls_createdby_calls_tenant_and_more"),
    ]

    operations = [
       
    ]
