# Generated by Django 4.1 on 2024-09-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        ('contacts', '0002_initial'),
        ('interaction', '0004_calls_call_to_calls_createdby_calls_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='business_phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]