# Generated by Django 4.1 on 2024-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_calls_call_to_calls_createdby_calls_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mapped',
            field=models.BooleanField(default=False),
        ),
    ]
