# Generated by Django 4.1 on 2024-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BehavioralMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_count", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
                ("engagement_score", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=255, unique=True)),
                ("messages", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("email", "Email"),
                            ("call", "Call"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("email", "Email"),
                            ("call", "Call"),
                        ],
                        max_length=50,
                    ),
                ),
                ("userid", models.CharField(max_length=5000)),
                ("mapped", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.IntegerField()),
                ("joy_score", models.FloatField()),
                ("sadness_score", models.FloatField()),
                ("anger_score", models.FloatField()),
                ("trust_score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
