# Generated by Django 4.1 on 2024-09-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0003_behavioralmetrics_user_conversation_user_and_more"),
    ]

    operations = [
 
    ]
