# Generated by Django 4.1 on 2024-10-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0005_behavioralmetrics_user_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralmetrics',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='contact_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
