# Generated by Django 4.1 on 2024-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_behavioralmetrics_user_conversation_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='dominant_emotion',
            field=models.CharField(default='happy', max_length=50),
            preserve_default=False,
        ),
    ]
