# Generated by Django 4.1 on 2024-09-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("accounts", "0001_initial"),
        ("stage", "0001_initial"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Opportunity Amount",
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "NONE"),
                            ("CALL", "CALL"),
                            ("EMAIL", " EMAIL"),
                            ("EXISTING CUSTOMER", "EXISTING CUSTOMER"),
                            ("PARTNER", "PARTNER"),
                            ("PUBLIC RELATIONS", "PUBLIC RELATIONS"),
                            ("CAMPAIGN", "CAMPAIGN"),
                            ("WEBSITE", "WEBSITE"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Source of Lead",
                    ),
                ),
                ("probability", models.IntegerField(blank=True, default=0, null=True)),
                ("closedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("closedOn", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("createdBy", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "createdOn",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                ("isActive", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="accounts.account",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity",
                        to="contacts.contact",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stage.stage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
        ),
    ]
